image: Visual Studio 2019

cache: c:\tools\vcpkg\installed\

install:
- cd C:\Tools\vcpkg
- git pull
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
- vcpkg install gtest:x86-windows
- vcpkg install gtest:x64-windows
