image: Visual Studio 2019

install:
  - nuget restore

platform:
  - x64

configuration:
  - Debug

test_script:
  - 'powershell.exe -executionpolicy ByPass -file %APPVEYOR_BUILD_FOLDER%\run_tests.ps1 -project_dir %APPVEYOR_BUILD_FOLDER%'
