image: Visual Studio 2019

cache: c:\tools\vcpkg\installed\

install:
- git clone https://github.com/Microsoft/vcpkg C:\Tools\vcpkg
- cd C:\Tools\vcpkg
- .\bootstrap-vcpkg.bat
- cd %APPVEYOR_BUILD_FOLDER%
- vcpkg install gtest:x86-windows
- vcpkg install gtest:x64-windows
